apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  labels:
    role: feedback-service
spec:
  selector: 
    app: feedback-service
  ports:
    - protocol: TCP
      port: 8002
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: feedback-service
  labels:
    role: feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
        - name: feedback-service
          image: srebrovn/feedback-service:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8002"  # Bind to port 8002
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_CONNECTION_STRING
          ports:
            - containerPort: 8002
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health/db
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10