apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  labels:
    role: feedback-service
spec:
  selector: 
    app: feedback-service
  ports:
    - protocol: TCP
      port: 8002
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: feedback-service
  labels:
    role: feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
        - name: feedback-service
          image: srebrovn/feedback-service:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8002