apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  JWT_TOKEN_ISSUER: aHR0cHM6Ly9tZWRpY29ubmVjdC5jb20=                  # Base64-encoded
  JWT_AUDIENCE: VXNlclNlcnZpY2U=                                  # Base64-encoded
  JWT_SIGNING_KEY: TXlKV1RTaWduaW5nS2V5TmVlZHNUb0JlQXRsZWFzdDI1NkJpdHM=    # Base64-encoded
  DB_CONNECTION_STRING: U2VydmVyPXRjcDptZWRpLWNvbm5lY3Qtc2VydmVyLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPW1lZGljb25uZWN0LWRiO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPW1jLWFkbWluO1Bhc3N3b3JkPU1lZGlDb25uZWN0MTIzO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz1GYWxzZTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1GYWxzZTs=
