apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-frontend-service
  labels:
    app: mc-frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-frontend-service
  template:
    metadata:
      labels:
        app: mc-frontend-service
    spec:
      containers:
        - name: mc-frontend-service
          image: makedonkabinova/mc-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mc-frontend-service
spec:
  selector:
    app: mc-frontend-service
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 80
  type: ClusterIP
