apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    role: appointment-service
spec:
  selector: 
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8004
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: appointment-service
  labels:
    role: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: srebrovn/appointment-service:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8004"  # Bind to port 8004
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_CONNECTION_STRING
          ports:
            - containerPort: 8004