apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  labels:
    role: doctor-service
spec:
  selector: 
    app: doctor-service
  ports:
    - protocol: TCP
      port: 8003
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doctor-service
  labels:
    role: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: srebrovn/doctor-service:v1.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8003