apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  labels:
    role: doctor-service
spec:
  selector: 
    app: doctor-service
  ports:
    - protocol: TCP
      port: 8003
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doctor-service
  labels:
    role: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: srebrovn/doctor-service:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8003"  # Bind to port 8003
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_CONNECTION_STRING
          ports:
            - containerPort: 8003
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health/db
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10