apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deployment
  labels:
    app: doctor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-deployment
  template:
    metadata:
      labels:
        app: doctor-deployment
    spec:
      containers:
        - name: doctor-deployment
          image: makedonkabinova/mc-doctor-management:latest #to update this
          ports:
            - containerPort: 8003
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
