name: Test Docker and Kubernetes Connectivity

on:
  workflow_dispatch: # Enables manual trigger for the workflow

jobs:
  test-connectivity:
    name: Test Docker and Kubernetes Connection
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      #####################################
      # Test Docker Hub Connection        #
      #####################################
      - name: Log in to Docker Hub
        id: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker Login
        run: |
          echo "Testing Docker Hub connection..."
          docker info | grep "Username"
        # If successful, docker info will output the Docker Hub username

      #####################################
      # Test Kubernetes Connection        #
      #####################################

      # Step 3: Decode and Configure KUBECONFIG
      - name: Set up Kubernetes kubeconfig
        run: |
          echo "Decoding KUBECONFIG_FILE..."
          echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      # Step 4: Verify Kubernetes Connection
      - name: Test Kubernetes Connection
        run: |
          echo "Testing Kubernetes cluster connection..."
          kubectl get nodes